baseURL = '/'
languageCode = 'en-us'
title = 'Play Chrome Dino Game Online - Blog'
theme = 'hugo-paper'

[params]
  author = 'Admin'
  homeSubtitle = 'Play the classic Chrome Dino Game online. Fun, fast, and free for all ages!'

relativeURLs = true
canonifyURLs = true